### ISSUE TITLE
已经安装旧版微信，但是切换版本时只有最近的几个版本，怎么切换到更早的小程序版本？

### ISSUE THREAD

**Issue by HuangJT** [r3x5ur/RadiumWMPFInstaller#1]
是通过设置指令吗？
能否给出指令的一些示例？要切换回微信小程序版本11065（对应微信版本3.9.11.19），要怎么设置？

**Comment by r3x5ur** [comment]
目前只能读取到 [https://dldir1.qq.com/weixin/Windows/XPlugin/updateConfigWin.xml](https://dldir1.qq.com/weixin/Windows/XPlugin/updateConfigWin.xml) 的内容，太老的版本没去研究

**Comment by r3x5ur** [comment]
> 是通过设置指令吗？ 能否给出指令的一些示例？要切换回微信小程序版本11065（对应微信版本3.9.11.19），要怎么设置？

更新了，现在加上了自动回滚旧版本客户端的功能

**Comment by HuangJT** [comment]
👍👍👍
